/**
 * Setup script for Stripe product, unit price, and webhook.
 *
 * Usage:
 *   npx tsx scripts/setup-stripe.ts
 *
 * Prerequisites:
 *   - STRIPE_SECRET_KEY must be set in .env.local
 *   - APP_URL must be set in .env.local
 *
 * What it does:
 *   1. Creates 1 product (Solis SEO) in Stripe
 *   2. Creates a $1/unit/month recurring price (quantity = monthly dollar amount)
 *   3. Creates a webhook endpoint for your APP_URL
 *   4. Configures the billing portal
 *   5. Prints the env vars to paste into .env.local
 */

import { config } from 'dotenv'
config({ path: '.env.local' })
import Stripe from 'stripe'
import * as fs from 'fs'
import * as path from 'path'

const STRIPE_SECRET_KEY = process.env.STRIPE_SECRET_KEY
const APP_URL = process.env.APP_URL || 'http://localhost:3000'

if (!STRIPE_SECRET_KEY || STRIPE_SECRET_KEY.includes('REPLACE_ME')) {
  console.error('\n❌ STRIPE_SECRET_KEY not configured.')
  console.error('   1. Go to https://dashboard.stripe.com/apikeys')
  console.error('   2. Copy your Secret key (starts with sk_test_ or sk_live_)')
  console.error('   3. Set it in .env.local as STRIPE_SECRET_KEY=sk_test_...\n')
  process.exit(1)
}

const stripe = new Stripe(STRIPE_SECRET_KEY, { typescript: true })

const WEBHOOK_EVENTS: Stripe.WebhookEndpointCreateParams.EnabledEvent[] = [
  'checkout.session.completed',
  'customer.subscription.updated',
  'customer.subscription.deleted',
  'invoice.created',
  'invoice.payment_failed',
  'invoice.payment_succeeded',
]

async function main() {
  console.log('\n🚀 Solis SEO — Stripe Setup (Variable Pricing)\n')
  console.log(`   Mode: ${STRIPE_SECRET_KEY!.startsWith('sk_live_') ? '🔴 LIVE' : '🟢 TEST'}`)
  console.log(`   App URL: ${APP_URL}\n`)

  // Step 1: Create product
  console.log('📦 Creating product: Solis SEO...')
  const product = await stripe.products.create({
    name: 'Solis SEO — Servicio Mensual',
    description: 'Suscripcion mensual de Solis SEO Autopilot. Monto variable por unidad.',
    metadata: { app: 'solis-seo-autopilot' },
  })
  console.log(`   ✅ Product: ${product.id}\n`)

  // Step 2: Create $1/unit/month price
  console.log('💰 Creating unit price: $1/unit/month...')
  const price = await stripe.prices.create({
    product: product.id,
    unit_amount: 100, // $1.00 in cents
    currency: 'usd',
    recurring: { interval: 'month' },
    metadata: { app: 'solis-seo-autopilot', type: 'unit' },
  })
  console.log(`   ✅ Price: ${price.id} ($1/unit/month)\n`)
  console.log('   → quantity=49 cobra $49/mes, quantity=150 cobra $150/mes, etc.\n')

  // Step 3: Create webhook endpoint
  console.log('🔗 Creating webhook endpoint...')
  const webhookUrl = `${APP_URL}/api/stripe/webhook`

  let webhookSecret = ''
  try {
    const webhook = await stripe.webhookEndpoints.create({
      url: webhookUrl,
      enabled_events: WEBHOOK_EVENTS,
      description: 'Solis SEO Autopilot — subscription events',
      metadata: { app: 'solis-seo-autopilot' },
    })
    webhookSecret = webhook.secret || ''
    console.log(`   ✅ Webhook: ${webhookUrl}`)
    if (webhookSecret) {
      console.log(`   ✅ Secret: ${webhookSecret}\n`)
    } else {
      console.log(`   ⚠️  Secret not returned — grab it from the Stripe Dashboard\n`)
    }
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err)
    console.log(`   ⚠️  Webhook creation skipped: ${msg}`)
    console.log(`   → Create manually at https://dashboard.stripe.com/webhooks\n`)
  }

  // Step 4: Create billing portal configuration
  console.log('🏦 Creating billing portal configuration...')
  try {
    await stripe.billingPortal.configurations.create({
      business_profile: {
        headline: 'Solis SEO — Gestiona tu suscripción',
      },
      features: {
        subscription_cancel: { enabled: true, mode: 'at_period_end' },
        payment_method_update: { enabled: true },
        invoice_history: { enabled: true },
      },
    })
    console.log('   ✅ Billing portal configured\n')
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err)
    console.log(`   ⚠️  Portal config skipped: ${msg}\n`)
  }

  // Step 5: Output env vars
  const envBlock = [
    '',
    '# Stripe — Generated by scripts/setup-stripe.ts',
    `STRIPE_PRICE_UNIT=${price.id}`,
    webhookSecret ? `STRIPE_WEBHOOK_SECRET=${webhookSecret}` : '# STRIPE_WEBHOOK_SECRET=whsec_... (grab from Stripe Dashboard)',
  ].join('\n')

  console.log('━'.repeat(50))
  console.log('📋 Add these to your .env.local:\n')
  console.log(envBlock)
  console.log('\n' + '━'.repeat(50))

  // Step 6: Auto-update .env.local
  const envPath = path.resolve(__dirname, '..', '.env.local')
  try {
    let envContent = fs.readFileSync(envPath, 'utf-8')

    // Replace old price vars with new single unit price
    envContent = envContent.replace(/STRIPE_PRICE_STARTER=.*/g, '')
    envContent = envContent.replace(/STRIPE_PRICE_PRO=.*/g, '')
    envContent = envContent.replace(/STRIPE_PRICE_AGENCY=.*/g, '')

    if (envContent.includes('STRIPE_PRICE_UNIT=')) {
      envContent = envContent.replace(/STRIPE_PRICE_UNIT=.*/g, `STRIPE_PRICE_UNIT=${price.id}`)
    } else {
      envContent += `\nSTRIPE_PRICE_UNIT=${price.id}`
    }

    if (webhookSecret) {
      envContent = envContent.replace(/STRIPE_WEBHOOK_SECRET=.*/g, `STRIPE_WEBHOOK_SECRET=${webhookSecret}`)
    }

    // Clean up empty lines from removed vars
    envContent = envContent.replace(/\n{3,}/g, '\n\n')

    fs.writeFileSync(envPath, envContent)
    console.log('\n✅ .env.local updated automatically!')
  } catch {
    console.log('\n⚠️  Could not auto-update .env.local — copy the values above manually.')
  }

  console.log('\n🎉 Stripe setup complete!\n')
}

main().catch(err => {
  console.error('❌ Setup failed:', err.message)
  process.exit(1)
})
